version: '3.8'
services:
  holiday-service:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - prometheus
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin